import type { CapabilityProfile } from '../types/capability';

export const altairProfile: CapabilityProfile = {
  id: 'altair',
  name: 'Altair 160',
  vendor: 'Altair',
  models: ['160'],
  supportedRoles: {
    mode: {},
    effective_mode: {},
    stop_control: {},
    outdoor_air_temp: {},
    supply_air_temp: {},
    extract_air_temp: {},
    exhaust_air_temp: {},
    supply_airflow: {},
    extract_airflow: {},
    airflow: {},
    target_airflow: {},
    mapped_level: {},
    supply_fan_speed: {},
    extract_fan_speed: {},
    indoor_humidity: {},
    filter_remaining: {},
    boost_active: {},
    boost_remaining: {},
    boost_duration: {},
    start_boost: {},
    cancel_boost: {},
    override_duration: {},
    override_remaining: {},
    clear_override: {},
    calibration_result: {},
    calibration_available: {},
    calibration_status: {},
    calibration_progress: {},
    last_calibration: {},
    maximum_airflow: {},
    away_airflow: {},
    low_airflow: {},
    home_airflow: {},
    high_airflow: {},
    calibration_start_control: {},
    calibration_cancel_control: {},
    fault_active: {},
    frost_protection_active: {},
    // The Altair HA integration's shower-triggered auto-boost feature
    // exposes these three diagnostic entities (binary_sensor.altair_shower_detected,
    // sensor.altair_shower_trigger_temperature) plus the ESPHome pipe sensor
    // a user wires in themselves — see ha-altair-mvhr's shower_detector.py.
    shower_detected: {},
    shower_trigger_temperature: {},
    shower_peak_temperature: {},
    shower_rearm_temperature: {},
    shower_pipe_temperature: {},
    shower_temperature_rise: {},
    shower_detection_window: {},
    shower_rearm_temperature_drop: {},
    heat_recovery: {},
    cooling_recovery: {},
    heat_recovery_efficiency: {},
    heating_recovered_today: {},
    heating_recovered_month: {},
    heating_recovered_lifetime: {},
    cooling_recovered_today: {},
    cooling_recovered_month: {},
    cooling_recovered_lifetime: {},
    heating_savings_today: {},
    heating_savings_lifetime: {},
    cooling_savings_today: {},
    cooling_savings_lifetime: {},
    avoided_emissions_today: {},
    avoided_emissions_lifetime: {},
    weekly_schedule: {},
    schedule_control: {},
    schedule_enabled: {},
    current_scheduled_mode: {},
    next_scheduled_change: {},
    schedule_override_active: {},
    // bypass_state is intentionally absent — see unsupportedRoles below.
  },
  // Confirmed product fact, not a "not configured yet" default: the Altair
  // 160 has no summer bypass. See docs/manufacturers/altair.md.
  unsupportedRoles: ['bypass_state'],
};
